M48
; DRILL file {KiCad 8.0.7} date 2025-04-15T10:47:45+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-15T10:47:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X5.6652Y-4.4039
X5.6652Y-4.6315
T2
X4.3209Y-4.0354
X4.3209Y-5.0
X5.8268Y-4.0354
X5.8268Y-5.0
M30
